# Generated by Django 3.2.8 on 2021-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='picz')),
                ('des', models.TextField()),
            ],
        ),
    ]
