# Generated by Django 3.2.8 on 2021-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('imge', models.ImageField(upload_to='photos')),
                ('desc', models.TextField()),
            ],
        ),
    ]
